[env:esp32-2432s028r]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200

# Configurações de Build para o Hardware ESP32-2432S028R
build_flags =
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D TOUCH_CS=33
    -D TOUCH_IRQ=36
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1
    -D ESP32_DMA=1

lib_deps =
    TFT_eSPI @ ^2.5.43
    XPT2046_Touchscreen @ ^1.4
    QRCode @ ^0.0.1
    uBitcoin @ ^0.2.0 
    FS
    SPI
    SD
    SPIFFS


# Ajuste do LDF para encontrar as dependências corretamente
lib_ldf_mode = deep+
